apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: git-event-listener
spec:
  triggers:
    - binding:
        name: git-push-binding
      template:
        name: git-pipeline-trigger-template
