apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: git-event-listener
  # Optional: Add labels for organization
  # labels:
  #   app: web-app-demo
spec:
  # The service account that the EventListener will use to create PipelineRuns.
  # Ensure this service account has permissions to create pipelineruns.
  # In IBM Cloud CD, 'pipeline' is often the default, or you can specify your own.
  serviceAccountName: pipeline 
  triggers:
    - name: git-push-trigger # A unique name for this specific trigger within the EventListener
      bindings:
        - ref: git-push-binding # References the TriggerBinding defined above
      template:
        ref: git-pipeline-trigger-template # References the TriggerTemplate defined above
      
      # Optional: Interceptors help filter events and validate payloads for specific Git providers.
      # You would typically enable one of these based on your Git provider.
      # For example, for GitHub, it ensures only 'push' events are processed and validates the signature.
      interceptors:
        # Example for GitHub (uncomment if using GitHub)
        # - github:
        #     eventTypes: ["push"] # Only trigger on push events
        #     secretRef:
        #       secretName: github-webhook-secret # A Kubernetes Secret containing your GitHub webhook secret
        #       secretKey: secretToken # The key within the secret that holds the token
        
        # Example for GitLab (uncomment if using GitLab)
        # - gitlab:
        #     eventTypes: ["Push Hook"]
        #     secretRef:
        #       secretName: gitlab-webhook-secret # A Kubernetes Secret containing your GitLab webhook secret
        #       secretKey: secretToken

        # For other Git providers, you might need different interceptors or none if relying solely
        # on the generic webhook. Consult Tekton Triggers documentation for your specific provider.
