apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: git-pipeline-trigger-template

spec:
  params:
    # These parameters are extracted by the TriggerBinding from the Git webhook payload
    - name: pipeline_git_repo_url
      description: The URL of the Git repository.
    - name: pipeline_git_branch
      description: The Git branch that was pushed.

    # These parameters are required by your ibm-cloud-web-app-pipeline
    - name: pipeline_content_base_path
      description: Base subdirectory within the cloned repository (e.g., "my-project/deploy").
      default: "" # Matches the default in your pipeline.yaml

    # HashiCorp Cloud Platform (HCP) / Terraform Cloud Parameters
    - name: pipeline_hcp_tfe_token
      description: HashiCorp Cloud Platform Terraform API Token. (Marked as secret in pipeline)
    - name: pipeline_hcp_org_name
      description: HashiCorp Cloud Platform Organization Name.
    - name: pipeline_hcp_workspace_name
      description: HashiCorp Cloud Platform Workspace Name.

    # AWS Parameters
    - name: pipeline_ssh_private_key
      description: Private SSH key to access the provisioned EC2 instance. (Marked as secret in pipeline)
    - name: pipeline_aws_region
      description: The AWS region where the EC2 instance is deployed.
    - name: pipeline_aws_access_key_id
      description: Your AWS Access Key ID for authentication. (Marked as secret in pipeline)
    - name: pipeline_aws_secret_access_key
      description: Your AWS Secret Access Key for authentication. (Marked as secret in pipeline)

  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        # generateName creates a unique name for each PipelineRun (e.g., web-app-pipeline-run-abcde)
        generateName: web-app-pipeline-run-
        # Optional: Add labels to the PipelineRun for easier filtering/monitoring
        labels:
          tekton.dev/pipeline: ibm-cloud-web-app-pipeline
          trigger: git-push
      spec:
        # Reference your existing pipeline
        pipelineRef:
          name: ibm-cloud-web-app-pipeline
        
        # Map the parameters from the TriggerTemplate to the Pipeline
        params:
          - name: git-repo-url
            value: $(params.pipeline_git_repo_url)
          - name: git-branch
            # Tekton's string replacement to get just the branch name from "refs/heads/main"
            value: $(params.pipeline_git_branch)
          - name: content-base-path
            value: $(params.pipeline_content_base_path)
          - name: hcp-tfe-token
            value: $(params.pipeline_hcp_tfe_token)
          - name: hcp-org-name
            value: $(params.pipeline_hcp_org_name)
          - name: hcp-workspace-name
            value: $(params.pipeline_hcp_workspace_name)
          - name: ssh-private-key
            value: $(params.pipeline_ssh_private_key)
          - name: aws-region
            value: $(params.pipeline_aws_region)
          - name: aws-access-key-id
            value: $(params.pipeline_aws_access_key_id)
          - name: aws-secret-access-key
            value: $(params.pipeline_aws_secret_access_key)
        
        # Define the workspace for the PipelineRun.
        # This should match the workspace defined in your pipeline.yaml and be backed by a PVC.
        workspaces:
          - name: pipeline-workspace
            # Replace 'your-pipeline-pvc' with the actual name of your PersistentVolumeClaim
            # that your Tekton pipelines use for their workspace.
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc # <-- IMPORTANT: Update this to your PVC name
