apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ibm-cloud-web-app-pipeline
spec:
  # Define parameters that will be passed into the pipeline
  params:
    - name: git-repo-url
      type: string
      description: The URL of the Git repository containing Terraform, Ansible, and app code.
    - name: git-branch
      type: string
      description: The Git branch to clone.
      default: main
    - name: content-base-path
      type: string
      description: Base subdirectory within the cloned repository where 'terraform-configs' and 'ansible-playbooks' are located (e.g., "my-project/deploy"). Default is empty if they are in the repo root.
      default: ""
    - name: hcp-tfe-token
      type: string
      description: HashiCorp Cloud Platform Terraform API Token.
      secret: true
    - name: hcp-org-name
      type: string
      description: HashiCorp Cloud Platform Organization Name.
    - name: hcp-workspace-name
      type: string
      description: HashiCorp Cloud Platform Workspace Name where Terraform will run.
    - name: ssh-private-key
      type: string
      description: Private SSH key to access the provisioned IBM Cloud VSI.
      secret: true
    - name: aws-region
      type: string
      description: The AWS region where the EC2 instance is deployed.
    - name: aws-access-key-id
      type: string
      description: Your AWS Access Key ID for authentication.
      secret: true
    - name: aws-secret-access-key
      type: string
      description: Your AWS Secret Access Key for authentication.
      secret: true

  # Define workspaces for sharing data between tasks
  workspaces:
    - name: pipeline-workspace # This is the main pipeline workspace

  # Define the tasks that make up your pipeline
  tasks:
    # 1. Task to clone the Git repository (inlined, using pipeline params)
    - name: clone-repository
      workspaces:
        - name: output
          workspace: pipeline-workspace
      taskSpec:
        workspaces:
          - name: output
        steps:
          - name: git-clone-step
            image: alpine/git:latest
            script: |
              set -eu
              GIT_REPO_URL="$(params.git-repo-url)"
              GIT_BRANCH="$(params.git-branch)"
              DEST_PATH="$(workspaces.output.path)"

              echo "Cloning repository: ${GIT_REPO_URL} branch: ${GIT_BRANCH}"

              if [ -d "$DEST_PATH" ]; then
                echo "Destination path '$DEST_PATH' already exists. Cleaning up contents..."
                rm -rf "${DEST_PATH}"/* "${DEST_PATH}"/.[!.]* || true 
              fi

              git clone --depth=1 --branch="${GIT_BRANCH}" "${GIT_REPO_URL}" "${DEST_PATH}"
              echo "Repository cloned successfully to ${DEST_PATH}/"
              ls -la "${DEST_PATH}"

    # 2. Task to provision infrastructure via HCP Terraform
    - name: provision-infrastructure
      runAfter: ["clone-repository"]
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: hcp-tfe-token
          value: $(params.hcp-tfe-token)
        - name: hcp-org-name
          value: $(params.hcp-org-name)
        - name: hcp-workspace-name
          value: $(params.hcp-workspace-name)
        - name: content-base-path
          value: $(params.content-base-path)
      taskSpec:
        workspaces:
          - name: source
        params:
          - name: hcp-tfe-token
            type: string
            secret: true
          - name: hcp-org-name
            type: string
          - name: hcp-workspace-name
            type: string
          - name: content-base-path
            type: string
        steps:
          - name: trigger-hcp-run
            image: ubuntu:latest
            script: |
              set -eu
              set -x # Enable shell debugging - IMPORTANT!

              echo "Updating apt cache and installing curl, jq..."
              apt-get update && apt-get install -y curl jq

              HCP_TFE_TOKEN="$(params.hcp-tfe-token)"
              HCP_ORG_NAME="$(params.hcp-org-name)"
              HCP_WORKSPACE_NAME="$(params.hcp-workspace-name)"
              
              REPO_BASE_PATH="$(params.content-base-path)"
              TERRAFORM_CONFIGS_DIR="$(workspaces.source.path)/${REPO_BASE_PATH}/terraform-configs"
              
              echo "Navigating to Terraform configuration directory: ${TERRAFORM_CONFIGS_DIR}"
              cd "${TERRAFORM_CONFIGS_DIR}"

              echo "Retrieving HCP Terraform Workspace ID for ${HCP_WORKSPACE_NAME}..."
              WORKSPACE_QUERY_RESPONSE=$(curl \
                --header "Authorization: Bearer ${HCP_TFE_TOKEN}" \
                --header "Content-Type: application/vnd.api+json" \
                "https://app.terraform.io/api/v2/organizations/${HCP_ORG_NAME}/workspaces?filter%5Bname%5D=${HCP_WORKSPACE_NAME}")
              
              echo "Raw Workspace Query Response:"
              echo "${WORKSPACE_QUERY_RESPONSE}"

              HCP_WORKSPACE_ID=$(echo "${WORKSPACE_QUERY_RESPONSE}" | jq -r '.data[0].id')

              if [ -z "$HCP_WORKSPACE_ID" ] || [ "$HCP_WORKSPACE_ID" = "null" ]; then
                echo "Error: Could not find HCP Terraform workspace ID for ${HCP_WORKSPACE_NAME}. Response: ${WORKSPACE_QUERY_RESPONSE}"
                exit 1
              fi
              echo "HCP Terraform Workspace ID: ${HCP_WORKSPACE_ID}"

              echo "Triggering new run in HCP Terraform..."
              RUN_RESPONSE=$(curl -X POST \
                --header "Authorization: Bearer ${HCP_TFE_TOKEN}" \
                --header "Content-Type: application/vnd.api+json" \
                --data-binary @- "https://app.terraform.io/api/v2/runs" <<EOF
              {
                "data": {
                  "attributes": {
                    "is-destroy": false,
                    "message": "Triggered by IBM Cloud CD Tekton pipeline"
                  },
                  "relationships": {
                    "workspace": {
                      "data": {
                        "type": "workspaces",
                        "id": "${HCP_WORKSPACE_ID}"
                      }
                    }
                  },
                  "type": "runs"
                }
              }
              EOF
              )
              echo "Raw Run Trigger Response:"
              echo "${RUN_RESPONSE}"

              RUN_ID=$(echo "$RUN_RESPONSE" | jq -r '.data.id')
              echo "HCP Terraform Run ID: ${RUN_ID}"

              if [ -z "$RUN_ID" ] || [ "$RUN_ID" = "null" ]; then
                echo "Error: Failed to trigger HCP Terraform run. Response: $RUN_RESPONSE"
                exit 1
              fi

              echo "Polling HCP Terraform run status. View run at: https://app.terraform.io/app/${HCP_ORG_NAME}/workspaces/${HCP_WORKSPACE_NAME}/runs/${RUN_ID}"
              RUN_STATUS=""
              
              # Loop until the run is in a terminal state (applied, errored, canceled, discarded)
              # OR it reaches 'needs_confirmation' for auto-approval
              while [ "$RUN_STATUS" != "applied" ] && \
                    [ "$RUN_STATUS" != "errored" ] && \
                    [ "$RUN_STATUS" != "canceled" ] && \
                    [ "$RUN_STATUS" != "discarded" ] && \
                    [ "$RUN_STATUS" != "needs_confirmation" ] && \ # Added needs_confirmation
                    [ "$RUN_STATUS" != "planned_and_finished" ]; do # <-- ADD THIS LINE
                
                echo "Current status: ${RUN_STATUS}. Waiting 15 seconds..."
                sleep 15
                
                RUN_STATUS_RESPONSE=$(curl \
                  --header "Authorization: Bearer ${HCP_TFE_TOKEN}" \
                  "https://app.terraform.io/api/v2/runs/${RUN_ID}")
                
                echo "Raw Run Status Response:"
                echo "${RUN_STATUS_RESPONSE}"
                RUN_STATUS=$(echo "${RUN_STATUS_RESPONSE}" | jq -r '.data.attributes.status')
                echo "Parsed RUN_STATUS: ${RUN_STATUS}"
              done

              echo "HCP Terraform run completed with status: ${RUN_STATUS}"

              # Check if the run needs confirmation and auto-approve it
              if [ "$RUN_STATUS" = "needs_confirmation" ]; then
                echo "Run needs confirmation. Auto-approving..."
                APPROVE_RESPONSE=$(curl -X POST \
                  --header "Authorization: Bearer ${HCP_TFE_TOKEN}" \
                  --header "Content-Type: application/vnd.api+json" \
                  "https://app.terraform.io/api/v2/runs/${RUN_ID}/actions/apply")
                
                echo "Raw Auto-Approve Response:"
                echo "${APPROVE_RESPONSE}"

                # Re-poll status after approval to wait for 'applied'
                RUN_STATUS="" # Reset status to re-enter loop
                echo "Waiting for run to apply after auto-approval..."
                while [ "$RUN_STATUS" != "applied" ] && \
                      [ "$RUN_STATUS" != "errored" ] && \
                      [ "$RUN_STATUS" != "canceled" ] && \
                      [ "$RUN_STATUS" != "discarded" ]; do
                  
                  echo "Current status: ${RUN_STATUS}. Waiting 15 seconds..."
                  sleep 15
                  
                  RUN_STATUS_RESPONSE=$(curl \
                    --header "Authorization: Bearer ${HCP_TFE_TOKEN}" \
                    "https://app.terraform.io/api/v2/runs/${RUN_ID}")
                  
                  echo "Raw Run Status Response:"
                  echo "${RUN_STATUS_RESPONSE}"
                  RUN_STATUS=$(echo "${RUN_STATUS_RESPONSE}" | jq -r '.data.attributes.status')
                  echo "Parsed RUN_STATUS: ${RUN_STATUS}"
                done
                echo "HCP Terraform run completed with status: ${RUN_STATUS} after auto-approval."
              fi

              # Final check for successful application
              if [ "$RUN_STATUS" = "applied" ] || [ "$RUN_STATUS" = "planned_and_finished" ]; then
                echo "HCP Terraform run completed successfully with status ${RUN_STATUS}"
              else
                echo "HCP Terraform run completed with status ${RUN_STATUS}, which is not a successful outcome."
                echo "Please check the run logs in HCP Terraform at https://app.terraform.io/app/${HCP_ORG_NAME}/workspaces/${HCP_WORKSPACE_NAME}/runs/${RUN_ID} for details."
                exit 1 # Failure for any other terminal status
              fi

              echo "Retrieving Terraform outputs..."
              TF_OUTPUTS_RESPONSE=$(curl --header "Authorization: Bearer ${HCP_TFE_TOKEN}" --header "Content-Type: application/vnd.api+json" "https://app.terraform.io/api/v2/workspaces/${HCP_WORKSPACE_ID}/current-state-version?include=outputs")
              
              echo "Raw Terraform Outputs Response:"
              echo "${TF_OUTPUTS_RESPONSE}"

              TF_OUTPUTS=$(echo "$TF_OUTPUTS_RESPONSE" | jq -r '.')

              WEB_SERVER_IP=$(echo "$TF_OUTPUTS" | jq -r '.included[] | select(.attributes.name=="web_server_public_ip") | .attributes.value')

              if [ -z "$WEB_SERVER_IP" ] || [ "$WEB_SERVER_IP" = "null" ]; then
                echo "Error Could not retrieve web_server_ip from HCP Terraform outputs. Raw outputs: ${TF_OUTPUTS_RESPONSE}"
                exit 1
              fi

              echo "Web Server IP ${WEB_SERVER_IP}"
              echo "WEB_SERVER_IP=${WEB_SERVER_IP}" > "$(workspaces.source.path)/web_server_ip.env"
              
              # Now exit successfully after all steps are complete
              exit 0 # Success!

    # 3. Task to deploy application with Ansible
# 3. Task to deploy application with Ansible
    - name: deploy-application
      runAfter: ["provision-infrastructure"]
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: ssh-private-key
          value: $(params.ssh-private-key)
        - name: content-base-path
          value: $(params.content-base-path)
        - name: aws-region
          value: $(params.aws-region)
        - name: git-repo-url
          value: $(params.git-repo-url)
        - name: git-branch
          value: $(params.git-branch)
        - name: aws-access-key-id
          value: $(params.aws-access-key-id)
        - name: aws-secret-access-key
          value: $(params.aws-secret-access-key)
      taskSpec:
        workspaces:
          - name: source
        params:
          - name: ssh-private-key
            type: string
            secret: true
          - name: content-base-path
            type: string
          - name: aws-region
            type: string
          - name: git-repo-url
            type: string
          - name: git-branch
            type: string
          - name: aws-access-key-id
            type: string
            secret: true
          - name: aws-secret-access-key
            type: string
            secret: true
        steps:
          - name: run-ansible-playbook-via-ssm
            image: ubuntu:latest
            script: |
              #!/bin/bash # <--- ADD THIS LINE
              set -eu
              set -x # Enable shell debugging

              echo "Updating apt cache and installing dependencies..."
              apt-get update
              apt-get install -y curl unzip jq sudo # Added sudo to be installed

              # --- Install AWS CLI v2 (Recommended Method for Linux) ---
              echo "Installing AWS CLI v2..."
              # Download the installer
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              # Unzip it
              unzip awscliv2.zip
              # Run the installer. Default location is /usr/local/bin/aws
              sudo ./aws/install

              # Verify AWS CLI installation
              aws --version
              echo "AWS CLI installed successfully."
              # --- End AWS CLI installation ---
              
              # --- Configure AWS Credentials from Tekton Parameters ---
              echo "Setting AWS Credentials from pipeline parameters..."
              export AWS_ACCESS_KEY_ID="$(params.aws-access-key-id)"
              export AWS_SECRET_ACCESS_KEY="$(params.aws-secret-access-key)"
              # AWS_REGION is already available via --region flag, but can also be set as an env var if preferred.
              # export AWS_DEFAULT_REGION="$(params.aws-region)"
              # --- End AWS Credentials Configuration ---

              # Source the IP from the previous task (web_server_public_ip)
              . "$(workspaces.source.path)/web_server_ip.env"
              echo "Loaded WEB_SERVER_IP: $WEB_SERVER_IP"

              # --- Retrieve EC2 Instance ID ---
              INSTANCE_ID=$(aws ec2 describe-instances \
                --region "$(params.aws-region)" \
                --filters "Name=network-interface.association.public-ip,Values=${WEB_SERVER_IP}" \
                --query "Reservations[0].Instances[0].InstanceId" \
                --output text)

              if [ -z "$INSTANCE_ID" ] || [ "$INSTANCE_ID" = "None" ]; then
                echo "Error: Could not find EC2 Instance ID for public IP ${WEB_SERVER_IP}"
                exit 1
              fi
              echo "Found EC2 Instance ID: ${INSTANCE_ID}"

              # Capture Tekton parameters into shell variables for direct embedding in SSM_COMMANDS
              LOCAL_GIT_REPO_URL="$(params.git-repo-url)"
              LOCAL_GIT_BRANCH="$(params.git-branch)"
              LOCAL_CONTENT_BASE_PATH="$(params.content-base-path)"
              LOCAL_PLAYBOOK_RELATIVE_PATH="ansible-playbooks" # This should be consistent with your repo structure

              # Full command string to be sent to SSM.
              # Variables like ${LOCAL_GIT_REPO_URL} are expanded here by the Tekton shell
              # BEFORE the string is sent to AWS SSM.
              read -r -d '' SSM_COMMANDS << 'EOF_SSM_COMMANDS' # <-- Add single quotes around the delimiter              #!/bin/bash
              set -eu
              set -x # Enable debugging within the SSM script

              echo "Starting SSM script execution."

              echo "Installing Ansible and Git..."
              sudo apt-get update
              sudo apt-get install -y ansible git # Ensure ansible is installed

              echo "Cloning repository: ${LOCAL_GIT_REPO_URL} branch: ${LOCAL_GIT_BRANCH}"
              echo "Attempting to set REPO_DIR."
              REPO_DIR="/tmp/app_repo"
              echo "REPO_DIR after assignment: '${REPO_DIR}'" # <--- Add this debug line

              if [ -d "${REPO_DIR}" ]; then
                echo "REPO_DIR exists, cleaning up."
                sudo rm -rf "${REPO_DIR}"
              fi
              echo "Attempting git clone into: '${REPO_DIR}'" # <--- Add this debug line
              git clone --depth=1 --branch="${LOCAL_GIT_BRANCH}" "${LOCAL_GIT_REPO_URL}" "${REPO_DIR}"

              echo "Git clone completed." clone --depth=1 --branch="${LOCAL_GIT_BRANCH}" "${LOCAL_GIT_REPO_URL}" "${REPO_DIR}"

              # Navigate to the playbook directory
              cd "${REPO_DIR}/${LOCAL_CONTENT_BASE_PATH}/${LOCAL_PLAYBOOK_RELATIVE_PATH}"

              # Create a local inventory file targeting 'localhost'
              echo "[localhost]" > inventory.ini
              echo "localhost ansible_connection=local" >> inventory.ini

              echo "Running Ansible playbook..."
              ansible-playbook -i inventory.ini playbook.yml
              EOF_SSM_COMMANDS

              # Prepare the parameters JSON for SSM using jq to properly escape and format.
              # This ensures the multi-line script is passed correctly as a single string
              # within the JSON array expected by --parameters.
              PARAMETERS_JSON=$(jq -n --arg cmd "${SSM_COMMANDS}" '{"commands": [$cmd]}')

              # Send the SSM command
              echo "Sending SSM Run Command to ${INSTANCE_ID}..."
              COMMAND_ID=$(aws ssm send-command \
                --region "$(params.aws-region)" \
                --instance-ids "${INSTANCE_ID}" \
                --document-name "AWS-RunShellScript" \
                --parameters "${PARAMETERS_JSON}" \
                --timeout-seconds 600 \
                --output text \
                --query "Command.CommandId")

              if [ -z "$COMMAND_ID" ] || [ "$COMMAND_ID" = "None" ]; then
                echo "Error: Failed to send SSM command."
                exit 1
              fi
              echo "SSM Command ID: ${COMMAND_ID}"

              # Wait for the SSM command to complete
              echo "Polling SSM command status..."
              while true; do
                COMMAND_STATUS=$(aws ssm list-command-invocations \
                  --region "$(params.aws-region)" \
                  --command-id "${COMMAND_ID}" \
                  --details \
                  --query "CommandInvocations[0].Status" \
                  --output text)

                echo "Current SSM status: ${COMMAND_STATUS}"
                if [[ "$COMMAND_STATUS" =~ ^(Success|Failed|Cancelled|TimedOut)$ ]]; then
                  break
                fi
                echo "Waiting 10 seconds..."
                sleep 10
              done
            
              echo "SSM command completed with status: ${COMMAND_STATUS}"
            
              if [ "$COMMAND_STATUS" = "Success" ]; then
                echo "Ansible playbook execution via SSM successful!"
                exit 0
              else
                echo "Ansible playbook execution via SSM failed. Check SSM logs for command ID ${COMMAND_ID} in AWS Console."
                exit 1
              fi
